enum LocationType {
   Planet = 'Planet',
   Cluster = 'Cluster',
   SpaceStation = 'Space station',
   Microverse = 'Microverse',
   TV = 'TV',
   Resort = 'Resort',
   FantasyTown = 'Fantasy town',
   Dream = 'Dream',
   Dimension = 'Dimension',
   Unknown = 'unknown',
   Menagerie = 'Menagerie',
   Game = 'Game',
   Customs = 'Customs',
   Daycare = 'Daycare',
   DwarfPlanet = 'Dwarf planet (Celestial Dwarf)',
   Miniverse = 'Miniverse',
   Teenyverse = 'Teenyverse',
   Box = 'Box',
   Spacecraft = 'Spacecraft',
   ArtificiallyGeneratedWorld = 'Artificially generated world',
   Machine = 'Machine',
   Arcade = 'Arcade',
   Spa = 'Spa',
   Quadrant = 'Quadrant',
   Quasar = 'Quasar',
   Mount = 'Mount',
   Liquid = 'Liquid',
   Convention = 'Convention',
   Woods = 'Woods',
   Diegesis = 'Diegesis',
   NonDiegeticAlternativeReality = 'Non-Diegetic Alternative Reality',
   Nightmare = 'Nightmare',
   Asteroid = 'Asteroid',
   AcidPlant = 'Acid Plant',
   Reality = 'Reality',
   DeathStar = 'Death Star',
   Base = 'Base',
   ElementalRings = 'Elemental Rings',
   Human = 'Human',
   Space = 'Space',
   Hell = 'Hell',
   PoliceDepartment = 'Police Department',
   Country = 'Country',
   Consciousness = 'Consciousness',
   Memory = 'Memory',
   All = 'All',
}

export const arrLocationType: LocationType[] = [
   LocationType.Planet,
   LocationType.Cluster,
   LocationType.SpaceStation,
   LocationType.Microverse,
   LocationType.TV,
   LocationType.Resort,
   LocationType.FantasyTown,
   LocationType.Dream,
   LocationType.Dimension,
   LocationType.Unknown,
   LocationType.Menagerie,
   LocationType.Game,
   LocationType.Customs,
   LocationType.Daycare,
   LocationType.DwarfPlanet,
   LocationType.Miniverse,
   LocationType.Teenyverse,
   LocationType.Box,
   LocationType.Spacecraft,
   LocationType.ArtificiallyGeneratedWorld,
   LocationType.Machine,
   LocationType.Arcade,
   LocationType.Spa,
   LocationType.Quadrant,
   LocationType.Quasar,
   LocationType.Mount,
   LocationType.Liquid,
   LocationType.Convention,
   LocationType.Woods,
   LocationType.Diegesis,
   LocationType.NonDiegeticAlternativeReality,
   LocationType.Nightmare,
   LocationType.Asteroid,
   LocationType.AcidPlant,
   LocationType.Reality,
   LocationType.DeathStar,
   LocationType.Base,
   LocationType.ElementalRings,
   LocationType.Human,
   LocationType.Space,
   LocationType.Hell,
   LocationType.PoliceDepartment,
   LocationType.Country,
   LocationType.Consciousness,
   LocationType.Memory,
   LocationType.All,
];

enum LocationsDimension {
   DimensionC137 = 'Dimension C-137',
   Unknown = 'unknown',
   PostApocalypticDimension = 'Post-Apocalyptic Dimension',
   ReplacementDimension = 'Replacement Dimension',
   CronenbergDimension = 'Cronenberg Dimension',
   FantasyDimension = 'Fantasy Dimension',
   Dimension5126 = 'Dimension 5-126',
   TesticleMonsterDimension = 'Testicle Monster Dimension',
   CromulonDimension = 'Cromulon Dimension',
   DimensionC500A = 'Dimension C-500A',
   DimensionK83 = 'Dimension K-83',
   DimensionJ19ζ7 = 'Dimension J19ζ7',
   EricStoltzMaskDimension = 'Eric Stoltz Mask Dimension',
   EvilRicksTargetDimension = "Evil Rick's Target Dimension",
   GiantTelepathicSpidersDimension = 'Giant Telepathic Spiders Dimension',
   UnknownDimension = 'Unknown dimension',
   DimensionK22 = 'Dimension K-22',
   DimensionD99 = 'Dimension D-99',
   DimensionD716 = 'Dimension D716',
   DimensionD716B = 'Dimension D716-B',
   DimensionD716C = 'Dimension D716-C',
   DimensionJ22 = 'Dimension J-22',
   DimensionC35 = 'Dimension C-35',
   PizzaDimension = 'Pizza Dimension',
   PhoneDimension = 'Phone Dimension',
   ChairDimension = 'Chair Dimension',
   FascistDimension = 'Fascist Dimension',
   FascistShrimpDimension = 'Fascist Shrimp Dimension',
   FascistTeddyBearDimension = 'Fascist Teddy Bear Dimension',
   WaspDimension = 'Wasp Dimension',
   TuskDimension = 'Tusk Dimension',
   MagicDimension = 'Magic Dimension',
   MergedDimension = 'Merged Dimension',
   All = 'All',
}

export const arrLocationsDimension: LocationsDimension[] = [
   LocationsDimension.DimensionC137,
   LocationsDimension.Unknown,
   LocationsDimension.PostApocalypticDimension,
   LocationsDimension.ReplacementDimension,
   LocationsDimension.CronenbergDimension,
   LocationsDimension.FantasyDimension,
   LocationsDimension.Dimension5126,
   LocationsDimension.TesticleMonsterDimension,
   LocationsDimension.CromulonDimension,
   LocationsDimension.DimensionC500A,
   LocationsDimension.DimensionK83,
   LocationsDimension.DimensionJ19ζ7,
   LocationsDimension.EricStoltzMaskDimension,
   LocationsDimension.EvilRicksTargetDimension,
   LocationsDimension.GiantTelepathicSpidersDimension,
   LocationsDimension.UnknownDimension,
   LocationsDimension.DimensionK22,
   LocationsDimension.DimensionD99,
   LocationsDimension.DimensionD716,
   LocationsDimension.DimensionD716B,
   LocationsDimension.DimensionD716C,
   LocationsDimension.DimensionJ22,
   LocationsDimension.DimensionC35,
   LocationsDimension.PizzaDimension,
   LocationsDimension.PhoneDimension,
   LocationsDimension.ChairDimension,
   LocationsDimension.FascistDimension,
   LocationsDimension.FascistShrimpDimension,
   LocationsDimension.FascistTeddyBearDimension,
   LocationsDimension.WaspDimension,
   LocationsDimension.TuskDimension,
   LocationsDimension.MagicDimension,
   LocationsDimension.MergedDimension,
   LocationsDimension.All,
];
